create table if not exists public.readers (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  country text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  utm_content text,
  utm_term text,
  referrer text,
  landing_page text,
  created_at timestamptz not null default now()
);

alter table public.readers enable row level security;

drop policy if exists "public can insert readers" on public.readers;
create policy "public can insert readers"
on public.readers
for insert
to anon
with check (true);

-- لا تنشئي سياسة SELECT للـ anon.
-- الموقع يستطيع إضافة التسجيل فقط، ولا يستطيع قراءة قائمة المشتركين.
